version: '3.8'

services:
  ai-trading-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - ai-trading-dev-network

networks:
  ai-trading-dev-network:
    driver: bridge
