version: '3.8'

services:
  ai-trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # For development, you can mount the source code
      # - .:/app
      # - /app/node_modules
      # - /app/.next
      # For logs and data persistence
      - ai-trading-data:/app/data
    restart: unless-stopped
    networks:
      - ai-trading-network

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - ai-trading-app
  #   networks:
  #     - ai-trading-network

volumes:
  ai-trading-data:

networks:
  ai-trading-network:
    driver: bridge
